# Generated by Django 4.0.4 on 2022-06-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_usuario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duennio',
            name='idDuennio',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Chip de la Mascota'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idusu',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo de usuario'),
        ),
    ]
