# Generated by Django 4.0.4 on 2022-06-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_duennio_idduennio_alter_usuario_idusu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fechNacimiento',
            field=models.DateTimeField(verbose_name='Fecha de nacimiento'),
        ),
    ]
