# Generated by Django 4.0.4 on 2022-06-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_usuario_fechnacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duennio',
            name='idDuennio',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Chip de la Mascota'),
        ),
    ]
