# Generated by Django 4.0.4 on 2022-06-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_usuario_fechnacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='idusu',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo de usuario'),
        ),
    ]
