# Generated by Django 4.0.4 on 2022-06-08 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_alter_comuna_idcomuna_alter_duennio_idduennio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atenciones',
            name='idTratamiento',
        ),
        migrations.RemoveField(
            model_name='atenciones',
            name='mascota',
        ),
        migrations.AddField(
            model_name='atenciones',
            name='numtratamiento',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='numero tratamiento'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='comuna',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.comuna'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mascota',
            name='nombreDuennio',
            field=models.CharField(default='nombre', max_length=20, verbose_name='nombre del dueño'),
        ),
        migrations.AlterField(
            model_name='comuna',
            name='idComuna',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='id de la comuna'),
        ),
        migrations.DeleteModel(
            name='Duennio',
        ),
    ]
