# Generated by Django 4.0.4 on 2022-06-08 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_remove_atenciones_idtratamiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='atencion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.atenciones'),
            preserve_default=False,
        ),
    ]
