# Generated by Django 4.0.4 on 2022-06-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_mascota_atencion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apellido',
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellidoUsuario',
            field=models.CharField(default='apellido', max_length=20, verbose_name='Apellido del usuario'),
        ),
    ]
