# Generated by Django 4.0.4 on 2022-06-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_duennio_idduennio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='idusu',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo de usuario'),
        ),
    ]
