# Generated by Django 4.0.4 on 2022-06-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_usuario_idusu'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rol_usuario',
            new_name='Rol',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='rol_usuario',
            new_name='rol',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contra',
            field=models.CharField(max_length=40, verbose_name='Contraseña del usuario'),
        ),
    ]
