# Generated by Django 4.0.4 on 2022-06-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_rename_rol_usuario_rol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fechNacimiento',
            field=models.DateTimeField(null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
